[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['php bin/cake.php cache clear_all || true']

[start]
cmd = 'php bin/cake.php server -H 0.0.0.0 -p $PORT'