[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer', 'php83Extensions.intl', 'php83Extensions.pdo', 'php83Extensions.pdo_pgsql', 'php83Extensions.mbstring']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-intl']

[phases.build]
cmds = ['php bin/cake.php cache clear_all || true']

[start]
cmd = 'php bin/cake.php server -H 0.0.0.0 -p $PORT'